### ISSUE TITLE
npm 包中不应该包含 .babelrc

### ISSUE THREAD

**Issue by relign** [lizhengnacl/post-message-im#1]
`npm` 包中不应该包含 `.babelrc` ，如果在 `babel-loader` 中不忽略 `node_modules` 或者这个包的话， 它将会被 `Webpack` 识别，并按照配置进行构建。
相关讨论：
https://github.com/airbnb/react-with-styles/issues/44
https://github.com/IdentityModel/oidc-client-js/pull/308

**Comment by lizhengnacl** [comment]
0.1.8中剔除了，升级下
